services:
  db:
    image: postgres:latest
    container_name: backend_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    working_dir: /app
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn --factory app.main:setup_app --host ${UVICORN_HOST} --port ${UVICORN_PORT}
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # Монтирование текущей директории в контейнер
      - ./voice_storage:/voice_storage  # Монтирование директории для аудиофайлов
    environment:
      - PULSE_SERVER=unix:/run/pulse/native  # Если нужно для PulseAudio

volumes:
  postgres_data:
