"""0007

Revision ID: 230ffe63172f
Revises: eb0f5a825f77
Create Date: 2025-02-13 18:52:07.472907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "230ffe63172f"
down_revision: Union[str, None] = "eb0f5a825f77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session", "current_step_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session", "current_step_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
