"""0006

Revision ID: eb0f5a825f77
Revises: eaea4cbf4f15
Create Date: 2025-02-11 23:41:15.823322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb0f5a825f77"
down_revision: Union[str, None] = "eaea4cbf4f15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column(
            "dialog_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "dialog_history")
    # ### end Alembic commands ###
